// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnG3j22MArLNJecA2b9WeeJu3Q_2gEp-M',
    appId: '1:775605373720:web:9a340d763f5e9e94af6c6d',
    messagingSenderId: '775605373720',
    projectId: 'lifeos-d47eb',
    authDomain: 'lifeos-d47eb.firebaseapp.com',
    storageBucket: 'lifeos-d47eb.firebasestorage.app',
    measurementId: 'G-SJWKBTL4WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxcgtx0HdW25pfueuPf7B__2TR_OWBkNM',
    appId: '1:775605373720:android:1cbf72ab6cef5400af6c6d',
    messagingSenderId: '775605373720',
    projectId: 'lifeos-d47eb',
    storageBucket: 'lifeos-d47eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcAfL6q13G7UE8YGnZ04XwyW7CpACvZYg',
    appId: '1:775605373720:ios:ce64540db811fcd7af6c6d',
    messagingSenderId: '775605373720',
    projectId: 'lifeos-d47eb',
    storageBucket: 'lifeos-d47eb.firebasestorage.app',
    androidClientId: '775605373720-vno9eu6ughijtbct8qe0hol39q485d7f.apps.googleusercontent.com',
    iosClientId: '775605373720-4peonqf3gqm1f1keuuelrbe8fs2dpjil.apps.googleusercontent.com',
    iosBundleId: 'com.lifeos.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcAfL6q13G7UE8YGnZ04XwyW7CpACvZYg',
    appId: '1:775605373720:ios:ce64540db811fcd7af6c6d',
    messagingSenderId: '775605373720',
    projectId: 'lifeos-d47eb',
    storageBucket: 'lifeos-d47eb.firebasestorage.app',
    androidClientId: '775605373720-vno9eu6ughijtbct8qe0hol39q485d7f.apps.googleusercontent.com',
    iosClientId: '775605373720-4peonqf3gqm1f1keuuelrbe8fs2dpjil.apps.googleusercontent.com',
    iosBundleId: 'com.lifeos.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnG3j22MArLNJecA2b9WeeJu3Q_2gEp-M',
    appId: '1:775605373720:web:f08531d9ebc20bd6af6c6d',
    messagingSenderId: '775605373720',
    projectId: 'lifeos-d47eb',
    authDomain: 'lifeos-d47eb.firebaseapp.com',
    storageBucket: 'lifeos-d47eb.firebasestorage.app',
    measurementId: 'G-34RFHFR6V7',
  );
}
